"""
CORE_AUTO - Fase 145: Contratto di locazione breve PDF precompilato (zero dipendenze).

Genera un PDF (1.4, scritto a mano in pura stdlib — niente reportlab) di un contratto di
locazione turistica breve, precompilato dai dati prenotazione. Importi in CENTESIMI interi.
PURO/deterministico (nessun timestamp implicito). XREF con offset corretti. Testo Latin-1,
caratteri non rappresentabili → '?'. BLINDATO: dati mancanti → segnaposto, mai eccezione.
"""
from __future__ import annotations

from typing import Any, Dict, List

PAGINA_W, PAGINA_H = 595, 842
MARGINE_X, TOP_Y, INTERLINEA, FONT = 50, 800, 16, 11


def _importo(cents: Any, valuta: Any) -> str:
    """Importo + valuta secondo i decimali VERI (JPY 0, KWD 3).

    Si chiamava `_euro` e divideva per cento sempre: sul contratto di un soggiorno da
    ¥54.000 stampava "540.00 JPY". E' un documento che le parti firmano — un importo
    sbagliato di cento volte li' dentro non e' un refuso, e' una clausola falsa.
    """
    c = cents if isinstance(cents, int) and not isinstance(cents, bool) and cents >= 0 else 0
    v = str(valuta or "EUR").strip().upper() or "EUR"
    try:
        from fase99_multicurrency import Denaro
        return Denaro(c, v).formatta()
    except Exception:
        return "%d %s" % (c, v)


def _g(d: Dict[str, Any], k: str, default: str = "________") -> str:
    v = d.get(k)
    return str(v) if v not in (None, "") else default


def componi_contratto(dati: Dict[str, Any], *, lingua: str = "it") -> List[str]:
    d = dati if isinstance(dati, dict) else {}
    it = lingua == "it"
    val = _g(d, "valuta", "EUR")
    if it:
        return [
            "CONTRATTO DI LOCAZIONE TURISTICA BREVE",
            "",
            "Locatore (host): " + _g(d, "host"),
            "Conduttore (ospite): " + _g(d, "guest"),
            "Immobile: " + _g(d, "alloggio") + " - " + _g(d, "citta"),
            "Periodo: dal " + _g(d, "check_in") + " al " + _g(d, "check_out"),
            "Numero ospiti: " + _g(d, "ospiti", "1"),
            "Corrispettivo totale: " + _importo(d.get("prezzo_cents"), val),
            "",
            "Le parti convengono la locazione dell'immobile per il solo periodo indicato,",
            "a uso turistico transitorio, ai sensi della normativa applicabile. Il",
            "conduttore si impegna alla riconsegna nello stato di fatto e al rispetto del",
            "regolamento della struttura. Il presente contratto e' precompilato dal",
            "sistema BookinVIP; il prezzo e' quello del preventivo firmato (non modificabile).",
            "",
            "Firma Locatore: __________________   Firma Conduttore: __________________",
            "Riferimento prenotazione: " + _g(d, "riferimento"),
        ]
    return [
        "SHORT-TERM RENTAL AGREEMENT",
        "",
        "Landlord (host): " + _g(d, "host"),
        "Tenant (guest): " + _g(d, "guest"),
        "Property: " + _g(d, "alloggio") + " - " + _g(d, "citta"),
        "Period: from " + _g(d, "check_in") + " to " + _g(d, "check_out"),
        "Number of guests: " + _g(d, "ospiti", "1"),
        "Total price: " + _importo(d.get("prezzo_cents"), val),
        "",
        "The parties agree to the rental of the property for the indicated period only,",
        "for transient tourist use, under applicable law. Generated by BookinVIP; the",
        "price is the signed quote (not modifiable).",
        "",
        "Landlord signature: ______________   Tenant signature: ______________",
        "Booking reference: " + _g(d, "riferimento"),
    ]


# Lettere europee che Latin-1 non ha: traslitterate restano leggibili e GIUSTE
# (Lukasz col L polacco diventava "?ukasz" sul contratto). Non e' un vezzo tipografico:
# e' il nome di una persona su un documento che firma.
_TRASLITTERA = {
    "\u0141": "L", "\u0142": "l",          # L/l polacca con barra
    "\u0160": "S", "\u0161": "s",          # S/s caron (ceco, croato)
    "\u017d": "Z", "\u017e": "z",          # Z/z caron
    "\u010c": "C", "\u010d": "c",          # C/c caron
    "\u0110": "D", "\u0111": "d",          # D/d con barra (croato)
    "\u0152": "OE", "\u0153": "oe",        # legatura OE
    "\u015e": "S", "\u015f": "s",          # S/s cediglia (turco, rumeno)
    "\u0162": "T", "\u0163": "t",          # T/t cediglia (rumeno)
    "\u0218": "S", "\u0219": "s",
    "\u021a": "T", "\u021b": "t",
    "\u0130": "I", "\u0131": "i",          # I turca con/senza punto
    "\u20ac": "EUR",                        # simbolo euro (non e' in Latin-1)
    "\u2013": "-", "\u2014": "-",          # trattini lunghi
    "\u2018": "'", "\u2019": "'",          # apostrofi tipografici
    "\u201c": '"', "\u201d": '"',
}


def rappresentabile(s: Any) -> bool:
    """Vero se il testo si puo' scrivere in questo PDF (font base = Latin-1).

    Serve a chi CHIAMA: un nome giapponese non e' traslitterabile, e stampare "????"
    sul contratto e' peggio che usare un ripiego ASCII (per esempio lo slug, che e'
    ASCII per costruzione).
    """
    try:
        _applica_traslitterazione(str(s)).encode("latin-1")
        return True
    except Exception:
        return False


def _applica_traslitterazione(s: str) -> str:
    return "".join(_TRASLITTERA.get(ch, ch) for ch in s)


def _escape(s: str) -> str:
    s = _applica_traslitterazione(str(s))
    out = []
    for ch in str(s):
        o = ord(ch)
        if ch in "()\\":
            out.append("\\" + ch)
        elif 32 <= o <= 255:
            out.append(ch)
        else:
            out.append("?")
    return "".join(out)


def _content_stream(righe: List[str]) -> bytes:
    body = ["BT", "/F1 %d Tf" % FONT, "%d %d Td" % (MARGINE_X, TOP_Y),
            "%d TL" % INTERLINEA]
    for r in righe:
        body.append("(%s) Tj" % _escape(r))
        body.append("T*")
    body.append("ET")
    return ("\n".join(body)).encode("latin-1", "replace")


def genera_pdf(dati: Dict[str, Any], *, lingua: str = "it") -> bytes:
    righe = componi_contratto(dati, lingua=lingua)
    contenuto = _content_stream(righe)
    objs = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        ("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 %d %d] /Resources << /Font << "
         "/F1 4 0 R >> >> /Contents 5 0 R >>" % (PAGINA_W, PAGINA_H)).encode("latin-1"),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length %d >>\nstream\n" % len(contenuto) + contenuto + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, o in enumerate(objs, start=1):
        offsets.append(len(out))
        out += ("%d 0 obj\n" % i).encode("latin-1") + o + b"\nendobj\n"
    xref_pos = len(out)
    out += ("xref\n0 %d\n" % (len(objs) + 1)).encode("latin-1")
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += ("%010d 00000 n \n" % off).encode("latin-1")
    out += ("trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n"
            % (len(objs) + 1, xref_pos)).encode("latin-1")
    return bytes(out)
